### PR TITLE
Remove files that are not needed since the old tests are gone

### PR DESCRIPTION
**Pull request by warpech**
@Mackiovello your commit https://github.com/StarcounterApps/Barcodes/commit/049cd05634ffc6eb4013cbefbb851eec29ebf1c3 missed two things that also should be removed.

- `package.json` should be removed from repo and `.sln` because it was only used for test script
- `test.js` reference should be removed from `.sln` because the file no longer exists

This PR fixes the above problem.

Can you pls check if other apps need this cleanup too?

### CODE REVIEW

**Comment by Mackiovello** [comment]
Looks good!

Should this be removed from `bower.json` too? https://github.com/StarcounterApps/Barcodes/blob/master/src/Barcodes/bower.json#L13

**Comment by Mackiovello** [comment]
> Can you pls check if other apps need this cleanup too?

Yes, I'll investigate that

**Comment by warpech** [comment]
> Should this be removed from bower.json too? https://github.com/StarcounterApps/Barcodes/blob/master/src/Barcodes/bower.json#L13

Actually the complete `ignore` section doesn't have any use. I have cleaned up `bower.json`.

**Comment by warpech** [comment]
Merging as done

**Pull request merged**
