### PR TITLE
Fix slots, add declarative-shadow-dom if needed

### PR DESCRIPTION
**Pull request by Mihaiii**
For https://github.com/Starcounter/RebelsLounge/issues/152

For `AppIconPage.html` I used `KitchenSink` as an example, but later on, for other apps, I put `declarative-shadow-dom` template outside of that template.

### CODE REVIEW

**Comment by Mihaiii** [comment]
I'm concerned about the comment I left about "AppIconPage" since the structure is different in PRs. Is one way prefered over the other?

**Comment by Mackiovello** [comment]
> I'm concerned about the comment I left about "AppIconPage" since the structure is different in PRs. Is one way prefered over the other?

I don't understand. It seems to be identical in the people app: https://github.com/StarcounterApps/People/pull/107/files

**Comment by Mihaiii** [comment]
Yes, there might be some few other examples that have this pattern, but there are also changes like this one: https://github.com/StarcounterApps/Calendar/pull/70/files#diff-fc0a2479f357332f3bacbbde01b4cb6d .
While working on this, at some point, it made more sense to me to apply changes like the one in "Calendar", even though in "KitchenSink" it's like here (Barcodes) or People.

**Comment by Mihaiii** [comment]
@PatrykSzwer whay do you think?

**Comment by PatrykSzwer** [comment]
As my personal preference I usually put the `declarative-shadow-dom` tag **inside** the base template in every page. For me It's most consistent to have one "parent" template that tangles all sections, dom-bind, scripts, and last but not least - declarative shadow dom template. I don't see the reason to change this structure for specific views, like AppIconPage. This could cause some misunderstandings and unneeded doubts and questions. @Mackiovello Do You agree with me? You should have right for final decision.

**Comment by Mackiovello** [comment]
I agree with you @PatrykSzwer. It's also described that way in the [Blending Guidelines](https://docs.starcounter.io/guides/web-apps/html-view-guidelines/)

**Comment by Mihaiii** [comment]
Ok, I'll make the changes everywhere according to this structure. 
@PatrykSzwer , could you please make the final reviews?

**Comment by PatrykSzwer** [comment]
Yes, make me reviewer and please fix conflicts before.

**Pull request merged**
